spring.application.name=${SPRING_APPLICATION_NAME:school-management}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:false}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:false}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH:/h2-console}

springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
